---

- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Wireguard
  ansible.builtin.apt:
    name: wireguard
    state: "{{ wireguard_state | default('present') }}"
