---

- name: "Enable IPv4 forward"
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  when: wireguard_ipv4_forwarding

- name: "Enable IPv6 forwarding"
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: true
    state: present
  when: wireguard_pv6_forwarding
