---

- name: Enable ip forwarding in /etc/sysctl.conf
  ansible.builtin.include_tasks: forwarding.yml
  when: wireguard_ipv4_forwarding or wireguard_ipv6_forwarding

- name: "Include tasks for {{ ansible_os_family }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: "Configure Wireguard"
  ansible.builtin.include_tasks: configure.yml
  loop: "{{ wireguard_config.keys() | list }}"
  loop_control:
    loop_var: wg_item
